version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - dataviz

  web:
    build: .
    # command: tail -F /dev/null
    # command: bash -c "dos2unix -n run.sh run.sh.converted && mv run.sh.converted run_win.sh && dos2unix -o run_win.sh && ./run_win.sh"
    volumes:
      - .:/code
    ports:
      - 8080:8080
    networks:
      - dataviz

networks:
  dataviz:
    driver: bridge

volumes:
    postgres:
